language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master
    - dev

cache:
  directories:
  - $HOME/.gradle

before_install:
  - chmod +x gradlew

install: true

script:
  - './gradlew clean setupCIWorkspace buildCI'
