language: java

jdk:
  - oraclejdk8

dist: trusty
sudo: required

branches:
  only:
    - master
    - dev

cache:
  directories:
  - $HOME/.gradle

before_install:
  - chmod +x gradlew

install: true

script:
  - './gradlew clean setupCIWorkspace buildCI'
