language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master
    - dev

cache:
  directories:
  - $HOME/.gradle

before_install:
  - chmod +x gradlew

install: true

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./gradlew clean setupCIWorkspace buildPR; else echo "No pull request: Upload to Bintray"; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./gradlew clean setupCIWorkspace build; else echo "Pull request: No upload to Bintray"; fi'
